title: Hraj Ascension!
baseURL: https://lostpeanut.github.io/hugo-start/
languageCode: cs-cz
publishDir: docs
googleAnalytics: UA-117957086-1

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Naša stránka sa zaoberá stolnou hrou Ascension. Poďte si zahrať s nami!
  authors: Majka, Vendy, Verča

